[workspace]
members = ["crates/app", "crates/wasm"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
uuid = { version = "1", features = ["serde", "v4"] }
safetensors = "0.4"
base64 = "0.22"
tokenizers = { version = "0.20", default-features = false, features = ["onig"] }
